const express = require('express')
const {twig} = require('twig')
const app = express()

app.set('view engine', 'twig')

const homeController = require('./Controller/home.Controller')



const drinkAController = require('./Controller/drinkA.Controller')
const drink1Controller = require('./Controller/drink/drink1.Controller')
const drink2Controller = require('./Controller/drink/drink2.Controller')
const drink3Controller = require('./Controller/drink/drink3.Controller')
const drink4Controller = require('./Controller/drink/drink4.Controller')
const drink5Controller = require('./Controller/drink/drink5.Controller')
const drink6Controller = require('./Controller/drink/drink6.Controller')
const drink7Controller = require('./Controller/drink/drink7.Controller')
const drink8Controller = require('./Controller/drink/drink8.Controller')
const drink9Controller = require('./Controller/drink/drink9.Controller')
const drink10Controller = require('./Controller/drink/drink10.Controller')
const drink11Controller = require('./Controller/drink/drink11.Controller')
const drink12Controller = require('./Controller/drink/drink12.Controller')
const drink13Controller = require('./Controller/drink/drink13.Controller')
const drink14Controller = require('./Controller/drink/drink14.Controller')
const drink15Controller = require('./Controller/drink/drink15.Controller')
const drink16Controller = require('./Controller/drink/drink16.Controller')
const drink17Controller = require('./Controller/drink/drink17.Controller')
const drink18Controller = require('./Controller/drink/drink18.Controller')
const drink19Controller = require('./Controller/drink/drink19.Controller')
const drink20Controller = require('./Controller/drink/drink20.Controller')

const foodAController = require('./Controller/foodA.Controller')
const foodaController = require('./Controller/food/fooda.Controller')
const foodbController = require('./Controller/food/foodb.Controller')
const foodcController = require('./Controller/food/foodc.Controller')
const fooddController = require('./Controller/food/foodd.Controller')
const food1Controller = require('./Controller/food/food1.Controller')
const food2Controller = require('./Controller/food/food2.Controller')
const food3Controller = require('./Controller/food/food3.Controller')
const food4Controller = require('./Controller/food/food4.Controller')
const food5Controller = require('./Controller/food/food5.Controller')
const food6Controller = require('./Controller/food/food6.Controller')
const food7Controller = require('./Controller/food/food7.Controller')
const food8Controller = require('./Controller/food/food8.Controller')
const food9Controller = require('./Controller/food/food9.Controller')
const food10Controller = require('./Controller/food/food10.Controller')
const food11Controller = require('./Controller/food/food11.Controller')
const food12Controller = require('./Controller/food/food12.Controller')
const food13Controller = require('./Controller/food/food13.Controller')
const food14Controller = require('./Controller/food/food14.Controller')
const food15Controller = require('./Controller/food/food15.Controller')
const food16Controller = require('./Controller/food/food16.Controller')
const food17Controller = require('./Controller/food/food17.Controller')
const food18Controller = require('./Controller/food/food18.Controller')
const food19Controller = require('./Controller/food/food19.Controller')
const food20Controller = require('./Controller/food/food20.Controller')

const dessertAController = require('./Controller/dessertA.Controller')
const dessert1Controller = require('./Controller/dessert/dessert1.Controller')
const dessert2Controller = require('./Controller/dessert/dessert2.Controller')
const dessert3Controller = require('./Controller/dessert/dessert3.Controller')
const dessert4Controller = require('./Controller/dessert/dessert4.Controller')
const dessert5Controller = require('./Controller/dessert/dessert5.Controller')
const dessert6Controller = require('./Controller/dessert/dessert6.Controller')
const dessert7Controller = require('./Controller/dessert/dessert7.Controller')
const dessert8Controller = require('./Controller/dessert/dessert8.Controller')
const dessert9Controller = require('./Controller/dessert/dessert9.Controller')
const dessert10Controller = require('./Controller/dessert/dessert10.Controller')
const dessert11Controller = require('./Controller/dessert/dessert11.Controller')
const dessert12Controller = require('./Controller/dessert/dessert12.Controller')
const dessert13Controller = require('./Controller/dessert/dessert13.Controller')
const dessert14Controller = require('./Controller/dessert/dessert14.Controller')
const dessert15Controller = require('./Controller/dessert/dessert15.Controller')
const dessert16Controller = require('./Controller/dessert/dessert16.Controller')
const dessert17Controller = require('./Controller/dessert/dessert17.Controller')
const dessert18Controller = require('./Controller/dessert/dessert18.Controller')
const dessert19Controller = require('./Controller/dessert/dessert19.Controller')
const dessert20Controller = require('./Controller/dessert/dessert20.Controller')



const restaurantsController = require('./Controller/restaurants.Controller')
const restaurantsaController = require('./Controller/restaurants/restaurantsa.Controller')
const restaurantsbController = require('./Controller/restaurants/restaurantsb.Controller')
const restaurantscController = require('./Controller/restaurants/restaurantsc.Controller')
const restaurantsdController = require('./Controller/restaurants/restaurantsd.Controller')
const restaurantseController = require('./Controller/restaurants/restaurantse.Controller')
const restaurantsfController = require('./Controller/restaurants/restaurantsf.Controller')
const restaurantsgController = require('./Controller/restaurants/restaurantsg.Controller')
const restaurants1Controller = require('./Controller/restaurants/restaurants1.Controller')
const restaurants2Controller = require('./Controller/restaurants/restaurants2.Controller')
const restaurants3Controller = require('./Controller/restaurants/restaurants3.Controller')
const restaurants4Controller = require('./Controller/restaurants/restaurants4.Controller')
const restaurants5Controller = require('./Controller/restaurants/restaurants5.Controller')
const restaurants6Controller = require('./Controller/restaurants/restaurants6.Controller')
const restaurants7Controller = require('./Controller/restaurants/restaurants7.Controller')
const restaurants8Controller = require('./Controller/restaurants/restaurants8.Controller')
const restaurants9Controller = require('./Controller/restaurants/restaurants9.Controller')
const restaurants10Controller = require('./Controller/restaurants/restaurants10.Controller')
const restaurants11Controller = require('./Controller/restaurants/restaurants11.Controller')
const restaurants12Controller = require('./Controller/restaurants/restaurants12.Controller')

const trickController = require('./Controller/trick.Controller')
const trick1Controller = require('./Controller/trick/trick1.Controller')
const trick2Controller = require('./Controller/trick/trick2.Controller')
const trick3Controller = require('./Controller/trick/trick3.Controller')
const trick4Controller = require('./Controller/trick/trick4.Controller')
const trick5Controller = require('./Controller/trick/trick5.Controller')
const trick6Controller = require('./Controller/trick/trick6.Controller')
const trick7Controller = require('./Controller/trick/trick7.Controller')
const trick8Controller = require('./Controller/trick/trick8.Controller')
const trick9Controller = require('./Controller/trick/trick9.Controller')
const trick10Controller = require('./Controller/trick/trick10.Controller')
const trick11Controller = require('./Controller/trick/trick11.Controller')
const trick12Controller = require('./Controller/trick/trick12.Controller')
const trick13Controller = require('./Controller/trick/trick13.Controller')
const trick14Controller = require('./Controller/trick/trick14.Controller')
const trick15Controller = require('./Controller/trick/trick15.Controller')
const trick16Controller = require('./Controller/trick/trick16.Controller')
const trick17Controller = require('./Controller/trick/trick17.Controller')
const trick18Controller = require('./Controller/trick/trick18.Controller')
const trick19Controller = require('./Controller/trick/trick19.Controller')
const trick20Controller = require('./Controller/trick/trick20.Controller')

const newsAController = require('./Controller/newsA.Controller')
const news1Controller = require('./Controller/News/news1.Controller')
const news2Controller = require('./Controller/News/news2.Controller')
const news3Controller = require('./Controller/News/news3.Controller')
const news4Controller = require('./Controller/News/news4.Controller')
const news5Controller = require('./Controller/News/news5.Controller')
const news6Controller = require('./Controller/News/news6.Controller')
const news7Controller = require('./Controller/News/news7.Controller')
const news8Controller = require('./Controller/News/news8.Controller')
const news9Controller = require('./Controller/News/news9.Controller')
const news10Controller = require('./Controller/News/news10.Controller')
const news11Controller = require('./Controller/News/news11.Controller')
const news12Controller = require('./Controller/News/news12.Controller')
const news13Controller = require('./Controller/News/news13.Controller')
const news14Controller = require('./Controller/News/news14.Controller')
const news15Controller = require('./Controller/News/news15.Controller')
const news16Controller = require('./Controller/News/news16.Controller')
const news17Controller = require('./Controller/News/news17.Controller')
const news18Controller = require('./Controller/News/news18.Controller')
const news19Controller = require('./Controller/News/news19.Controller')
const news20Controller = require('./Controller/News/news20.Controller')


app.get('/', homeController.index)
app.get('/home', homeController.index)


app.get('/drink-1', drinkAController.index)
app.get('/drink1', drink1Controller.index)
app.get('/drink2', drink2Controller.index)
app.get('/drink3', drink3Controller.index)
app.get('/drink4', drink4Controller.index)
app.get('/drink5', drink5Controller.index)
app.get('/drink6', drink6Controller.index)
app.get('/drink7', drink7Controller.index)
app.get('/drink8', drink8Controller.index)
app.get('/drink9', drink9Controller.index)
app.get('/drink10', drink10Controller.index)
app.get('/drink11', drink11Controller.index)
app.get('/drink12', drink12Controller.index)
app.get('/drink13', drink13Controller.index)
app.get('/drink14', drink14Controller.index)
app.get('/drink15', drink15Controller.index)
app.get('/drink16', drink16Controller.index)
app.get('/drink17', drink17Controller.index)
app.get('/drink18', drink18Controller.index)
app.get('/drink19', drink19Controller.index)
app.get('/drink20', drink20Controller.index)

app.get('/food-11', foodAController.index)
app.get('/food-1', foodaController.index)
app.get('/food-2', foodbController.index)
app.get('/food-3', foodcController.index)
app.get('/food-4', fooddController.index)
app.get('/food1', food1Controller.index)
app.get('/food2', food2Controller.index)
app.get('/food3', food3Controller.index)
app.get('/food4', food4Controller.index)
app.get('/food5', food5Controller.index)
app.get('/food6', food6Controller.index)
app.get('/food7', food7Controller.index)
app.get('/food8', food8Controller.index)
app.get('/food9', food9Controller.index)
app.get('/food10', food10Controller.index)
app.get('/food11', food11Controller.index)
app.get('/food12', food12Controller.index)
app.get('/food13', food13Controller.index)
app.get('/food14', food14Controller.index)
app.get('/food15', food15Controller.index)
app.get('/food16', food16Controller.index)
app.get('/food17', food17Controller.index)
app.get('/food18', food18Controller.index)
app.get('/food19', food19Controller.index)
app.get('/food20', food20Controller.index)


app.get('/dessert-1', dessertAController.index)
app.get('/dessert1', dessert1Controller.index)
app.get('/dessert2', dessert2Controller.index)
app.get('/dessert3', dessert3Controller.index)
app.get('/dessert4', dessert4Controller.index)
app.get('/dessert5', dessert5Controller.index)
app.get('/dessert6', dessert6Controller.index)
app.get('/dessert7', dessert7Controller.index)
app.get('/dessert8', dessert8Controller.index)
app.get('/dessert9', dessert9Controller.index)
app.get('/dessert10', dessert10Controller.index)
app.get('/dessert11', dessert11Controller.index)
app.get('/dessert12', dessert12Controller.index)
app.get('/dessert13', dessert13Controller.index)
app.get('/dessert14', dessert14Controller.index)
app.get('/dessert15', dessert15Controller.index)
app.get('/dessert16', dessert16Controller.index)
app.get('/dessert17', dessert17Controller.index)
app.get('/dessert18', dessert18Controller.index)
app.get('/dessert19', dessert19Controller.index)
app.get('/dessert20', dessert20Controller.index)


app.get('/restaurants-11', restaurantsController.index)
app.get('/r-1', restaurantsaController.index)
app.get('/r-2', restaurantsbController.index)
app.get('/r-3', restaurantscController.index)
app.get('/r-4', restaurantsdController.index)
app.get('/r-5', restaurantseController.index)
app.get('/r-6', restaurantsfController.index)
app.get('/r-7', restaurantsgController.index)
app.get('/restaurants1', restaurants1Controller.index)
app.get('/restaurants2', restaurants2Controller.index)
app.get('/restaurants3', restaurants3Controller.index)
app.get('/restaurants4', restaurants4Controller.index)
app.get('/restaurants5', restaurants5Controller.index)
app.get('/restaurants6', restaurants6Controller.index)
app.get('/restaurants7', restaurants7Controller.index)
app.get('/restaurants8', restaurants8Controller.index)
app.get('/restaurants9', restaurants9Controller.index)
app.get('/restaurants10', restaurants10Controller.index)
app.get('/restaurants11', restaurants11Controller.index)
app.get('/restaurants12', restaurants12Controller.index)

app.get('/trick', trickController.index)
app.get('/trick1', trick1Controller.index)
app.get('/trick2', trick2Controller.index)
app.get('/trick3', trick3Controller.index)
app.get('/trick4', trick4Controller.index)
app.get('/trick5', trick5Controller.index)
app.get('/trick6', trick6Controller.index)
app.get('/trick7', trick7Controller.index)
app.get('/trick8', trick8Controller.index)
app.get('/trick9', trick9Controller.index)
app.get('/trick10', trick10Controller.index)
app.get('/trick11', trick11Controller.index)
app.get('/trick12', trick12Controller.index)
app.get('/trick13', trick13Controller.index)
app.get('/trick14', trick14Controller.index)
app.get('/trick15', trick15Controller.index)
app.get('/trick16', trick16Controller.index)
app.get('/trick17', trick17Controller.index)
app.get('/trick18', trick18Controller.index)
app.get('/trick19', trick19Controller.index)
app.get('/trick20', trick20Controller.index)

app.get('/news-1', newsAController.index)
app.get('/news1', news1Controller.index)
app.get('/news2', news2Controller.index)
app.get('/news3', news3Controller.index)
app.get('/news4', news4Controller.index)
app.get('/news5', news5Controller.index)
app.get('/news6', news6Controller.index)
app.get('/news7', news7Controller.index)
app.get('/news8', news8Controller.index)
app.get('/news9', news9Controller.index)
app.get('/news10', news10Controller.index)
app.get('/news11', news11Controller.index)
app.get('/news12', news12Controller.index)
app.get('/news13', news13Controller.index)
app.get('/news14', news14Controller.index)
app.get('/news15', news15Controller.index)
app.get('/news16', news16Controller.index)
app.get('/news17', news17Controller.index)
app.get('/news18', news18Controller.index)
app.get('/news19', news19Controller.index)
app.get('/news20', news20Controller.index)

app.use('/assets', express.static(__dirname + '/static/assets',{
	maxAge: 86400000
}))
app.listen(8000, function(err) {
	console.log('server is running on port 8000')
}) 